### ISSUE TITLE
Abstracts Absatzdarstellung

### ISSUE THREAD

**Issue by myken** [guenterh/fsw#26]
Die Abstracts, die in die HS Datenbank eingefüllt werden, haben für die Absatzdarstellung kein HTML lesbares Zeichen. 
So sieht es in der DB aus:
http://www.hist.uzh.ch/static/intern/qualifikationsarbeiten/qualiarbeit_add_update.php?qarb_arb_id=1275
so auf der Website:

http://www.fsw.uzh.ch/forschung/lizenziatsarbeiten.html

**Comment by guenterh** [comment]
@myken 
Done see https://github.com/guenterh/fsw/commit/f7ccb3331178d2ba6fa549de03db864e8331975b
Günter
